### ISSUE TITLE
Dart 2 incompatible

### ISSUE THREAD

**Issue by RDiGregorio** [pavelgj/PathFinding.dart#1]
This project is one of the few lingering ones that haven't moved to Dart 2 yet. I'm using it in some live code right now and I'm going to have to drop the dependency if there aren't any plans for a port.

**Comment by pavelgj** [comment]
Sorry, I have no plans to upgrade to dart 2. I'll accept a pull request.

**Comment by RDiGregorio** [comment]
OK, I created a pull request.

**Comment by pavelgj** [comment]
Thanks for the PR! I'll try to push to pub asap.

**Comment by pavelgj** [comment]
Pushed https://pub.dartlang.org/packages/pathfinding/versions/2.0.0
